version: '3.8'

services:

  lib80:
    image: mnavarro/sqlx:8.0-dev
    build:
      context: .mnavarro/docker
      dockerfile: ./lib/Dockerfile80
      target: dev
    container_name: mmnavarro.sqlx.lib80.dev
    working_dir: /php/lib
    volumes:
      - .:/php/lib
    env_file: .env.test
    user: ${UID:-1000}

  lib81:
    image: mnavarro/sqlx:8.1-dev
    build:
      context: .mnavarro/docker
      dockerfile: ./lib/Dockerfile81
      target: dev
    container_name: mnavarro.sqlx.lib81.dev
    working_dir: /php/lib
    env_file: .env.test
    volumes:
      - .:/php/lib
    user: ${UID:-1000}

  postgres14:
    image: postgres:14-alpine
    container_name: mnavarro.sqlx.postgres14.dev
    environment:
      POSTGRES_USER: sqlx
      POSTGRES_PASSWORD: sqlx
      POSTGRES_DB: sqlx

  mysql57:
    image: mysql:5.7-debian
    container_name: mnavarro.sqlx.mysql57.dev
    environment:
      MYSQL_ROOT_PASSWORD: sqlx
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: sqlx
      MYSQL_USER: sqlx
      MYSQL_PASSWORD: sqlx
